version: "3"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
      - WEBUI_PORT=8080
    volumes:
      - /mnt/gd:/mnt/gd
      - /mnt/qbittorrent/appdata/config:/config
      - /mnt/qbittorrent/downloads:/downloads
    network_mode: host
    restart: unless-stopped

  qb_tools:
    build: .
    container_name: qb_tools
    environment:
      - TZ=Asia/Shanghai
    network_mode: host
    depends_on:
      - qbittorrent
